baseURL = 'https://nspeaks.com/'
languageCode = 'en-us'
title = 'NSpeaks'
theme = 'PaperMod'
pagination.pagerSize = 5
enableEmoji = true
Copyright = "<a href='/archives/'>Archives</a> | <a href='/privacy-policy'>Privacy Policy</a> <span>&copy; 2022 <a href='https://nspeaks.com'>NSpeaks</a></span>"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
disableHugoGeneratorInject = true

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = '/:slug'

[taxonomies]
category = 'category'
tag = 'tag'
series = "series"

[params]
env = "production"
title = "NSpeaks"
description = "Technology and Stuff."
keywords = [ "Technology", "Linux", "Servers", "WordPress" ]
author = ""
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShareButtons = [ "twitter", "reddit", "telegram", "facebook", "whatsapp" ]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
ShowFullTextinRSS = true
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
enableInlineShortcodes = true

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned.svg"
  disableHLJS = true

  [params.label]
  text = "NSpeaks"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my professional space where I share tutorials on Linux, and Server Administration. I may on occassion share random useful tips from any topic that I find of interest. If you want a Linux tutorial for your site, you can reach me on any of my socials below or you can <a href='mailto:navjot@nspeaks.com'>mail me</a>. I maintain a <a href='https://diary.nspeaks.com' title='Personal Blog'>personal blog</a> as well where I post random stuff and talk about movies and shows."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/nspeaks"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/772709/navjotjsingh"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/navjotjsingh"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@nspeaks"

  [[params.socialIcons]]
  name = "palestine"
  url = "https://www.aljazeera.com/news/2023/10/9/whats-the-israel-palestine-conflict-about-a-simple-guide"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
name = "About Me"
url = "about/"
weight = 2

[[menu.main]]
name = "Recommendations"
url = "ref/"
weight = 5

[[menu.main]]
identifier = "category"
name = "Categories"
url = "/category/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "tag"
name = "Tags"
url = "/tag/"
weight = 20

#[[menu.main]]
#identifier = "diary"
#name = "Personal Blog"
#url = "https://diary.nspeaks.com"
#weight = 30

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true
