baseURL = 'https://joyful-youtiao-629708.netlify.app/'
languageCode = 'en-us'
title = 'NSpeaks'
theme = 'PaperMod'
paginate = 5
enableEmoji = true
Copyright = "<a href='/archives/'>Archives</a> | <a href='/privacy-policy'>Privacy Policy</a> <span>&copy; 2022 <a href='https://nspeaks.com'>NSpeaks</a></span>"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = '/:slug'

[params]
env = "production"
title = "NSpeaks"
description = "Technology and Stuff."
keywords = [ "Technology", "Linux", "Servers", "WordPress" ]
author = "Navjot Singh"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShareButtons = [ "twitter", "reddit", "telegram", "facebook", "whatsapp" ]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
enableInlineShortcodes = true

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"
  disableHLJS = true

  [params.label]
  text = "NSpeaks"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my professional space where I share tutorials on Linux, and Server Administration. I may on occassion share random useful tips from any topic that I find of interest. You can reach me on any of my socials below or you can contact me at <a href='mailto:navjot@nspeaks.com'>navjot@nspeaks.com</a>."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/nspeaks_dev"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/772709/navjotjsingh"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/navjotjsingh"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
name = "About Me"
url = "about/"
weight = 2

#[[menu.main]]
#name = "Archives"
#url = "archives/"
#weight = 5

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "diary"
name = "Personal Blog"
url = "https://diary.nspeaks.com"
weight = 30

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
  
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4
  
  [markup.goldmark.renderer]
    unsafe = true
