[context.production.environment]
HUGO_VERSION = "0.123.0"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
from = "/cloudways"
to = "https://www.cloudways.com/en/managed-hosting-for-digital-ocean.php?id=56611"
status = 301
force = true

[[redirects]]
  from = "https://nspeaks.com/348/google-chrome-on-windows-2000-works-with-my-method/"
  to = "https://nspeaks.com/google-chrome-on-windows-20002k-works-with-my-method/"
  status = 301
  force = true

[[redirects]]
  from = "https://nspeaks.com/wp-content/uploads/2008/09/chrome2k.zip"
  to = "https://nspeaks.com/download/crm2k70.cab"
  status = 301
  force = true

[[redirects]]
from ="/masto"
to = "https://mastodon.social/@nspeaks"
status = 301
force = true

[[redirects]]
from ="/foss"
to = "https://fosstodon.org/@navjot"
status = 301
force = true

[[redirects]]
  from = "https://nspeaks.com/1014/template-changestags-for-wordpress-3-0/"
  to = "https://nspeaks.com/template-changestags-for-wordpress-3-0/"
  status = 301
  force = true

[[redirects]]
  from = "https://nspeaks.com/699/kill-ie6-now/"
  to = "https://nspeaks.com/kill-ie6-now/"
  status = 301
  force = true

[[redirects]]
  from = "http://nspeaks.com/1069/difference-between-is_home-and-is_front_page/"
  to = "https://nspeaks.com/difference-between-is_home-and-is_front_page/"
  status = 301
  force = true

[[redirects]]
  from = "https://nspeaks.com/978/insert-shortcodes-into-your-custom-fields/"
  to = "https://nspeaks.com/insert-shortcodes-into-your-custom-fields/"
  status = 301
  force = true
